usdot-fhwa-stol/carma-messenger

.circleci/config.yml
carma-messenger-core/docker/checkout.sh
docs/PULL_REQUEST_TEMPLATE.md

CI updates to allow circle to read errors from our CI scripts, and fixed link to Contributing.md in PULL_REQUEST_TEMPLATE.md
[#369](https://github.com/usdot-fhwa-stol/carma-platform/issues/369)
CircleCI is has been running successfully in spite of test failures. This was due to errors in our code coverage scripts not being passed to the CircleCI shell. This issue has been addressed by carma-base-3.7.1 release, which this PR is designed to incorporate into this repo.
Tested by breaking the test suite and confirming that Circle fails as expected.
[CARMA Contributing Guide](Contributing.md)

updated for carma-base-3.7.1 release

---

carma-messenger-core/j2735_convertor/src/j2735_convertor.cpp
carma-messenger-core/j2735_convertor/src/j2735_convertor.h

The files j2735_convertor.cpp and .h still had references to the old COntrolMessage message types. These messages were replaced by the TrafficControlMessage with PR: https://github.com/usdot-fhwa-stol/carma-messenger/pull/23, but this file was forgotten. 
usdot-fhwa-stol/carma-platform#749
Adding forgotten features from the above PR. 
This was tested by confirming these re-namings as the only changes and building the j2735_convertor. 

Updated message types in j2735_convertor

---

carma-messenger-ui/website/widgets/truckInspection/widget.js

ROS topics published message format changes require UI change. 
The UI should be able to read both current message format and new message format.
https://github.com/usdot-fhwa-stol/carma-platform/issues/880
ACE testing
Local integration testing and UI testing in vehicle
JS changes

Update CARMA messenger UI to consume the modified data format

---

carma-messenger-core/carma-messenger/launch/carma-messenger.launch
carma-messenger-core/truck_inspection_plugin/config/parameters.yaml
carma-messenger-core/truck_inspection_plugin/src/truck_inspection_plugin.cpp

Update mobility request header with values temprarily. Once the message node for mobility request fix is done, it will be updated.
https://github.com/usdot-fhwa-stol/carma-platform/issues/871
ACE testing
Integration testing
C++ and ymal files

update Mobility Request header ids and params number

---

carma-messenger-core/cpp_message/include/MobilityHeader_Message.h
carma-messenger-core/cpp_message/include/MobilityOperation_Message.h
carma-messenger-core/cpp_message/include/MobilityPath_Message.h
carma-messenger-core/cpp_message/include/MobilityRequest_Message.h
carma-messenger-core/cpp_message/include/MobilityResponse_Message.h
carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
carma-messenger-core/cpp_message/src/MobilityPath_Message.cpp
carma-messenger-core/cpp_message/src/MobilityRequest_Message.cpp
carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp

This change redefines the default string for mobility messages to "UNSET". MobilityOperation Strategy params default is changed to "[ ]"

changing default string

---

carma-messenger-core/cpp_message/src/BSM_Message.cpp
carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
carma-messenger-core/cpp_message/src/MobilityPath_Message.cpp
carma-messenger-core/cpp_message/src/MobilityRequest_Message.cpp
carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp

This is ascertained solely by inspection. I am not yet able to build and test the system. That said...
My understanding is that `uper_encode_to_buffer` provides, in the `encoded` member of the returned structure, the number of bits of packed data that were formatted. Unless there is a guarantee that the number of bits will always be a multiple of 8, there appears to be a possibility of losing the last byte.
In order to ensure that the final bits (when `ec.encoded % 8 != 0`) are copied, one additional byte must be copied. Therefore, instead of simply `ec.encoded / 8`, the extra bits must be taken into account with `(ec.encoded + 7) / 8`.
https://github.com/usdot-fhwa-stol/carma-platform/issues/972
It has not been tested. This was discovered solely by inspection.
- [ x] Defect fix …

Possibly lose one byte when copying formatted data

---

carma-messenger-core/cpp_message/src/BSM_Message.cpp

The potential bug is "use after free".
If `message` is freed before being used, depending on the local
implementation of `free`, the pointers within it might be zeroed or be
otherwise made invalid, and `asn_fprint` would then crash trying to
dereference those pointers. This change moves freeing of the buffer to
after its final use.
https://github.com/usdot-fhwa-stol/carma-platform/issues/971

If the human-readable print is uncommented, the code could crash

---

carma-messenger-config/chevrolet_tahoe_2018/docker-compose-background.yml
carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
carma-messenger-config/chevrolet_tahoe_2018/hooks/build
carma-messenger-config/chevrolet_tahoe_2018/hooks/pre_build
carma-messenger-config/development/docker-compose-background.yml
carma-messenger-config/development/docker-compose.yml
carma-messenger-config/development/hooks/build
carma-messenger-config/development/hooks/pre_build

This hotfix release adds docker build hooks to enable metadata in carma-messenger-config images.
[#948](https://github.com/usdot-fhwa-stol/carma-platform/issues/948)
Needed in order to display version number for carma-messenger-config
Employs the same build hook used by all other repos, which is successfully populating images with metadata

hotfix 1.0.2

---

carma-messenger-config/chevrolet_tahoe_2018/docker-compose-background.yml
carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
carma-messenger-config/development/docker-compose-background.yml
carma-messenger-config/development/docker-compose.yml
carma-messenger-core/Dockerfile

Dockerfile updates for carma-messenger-core to enable Vanden Plas candidate image to be built using the release/vanden-plas branch.
Updated the carma-messenger-core Dockerfile to reference usdotfhwastolcandidate/carma-base:vanden-plas as the base image in order to build the Vanden Plas candidate image for carma-messenger-core using the release/vanden-plas branch.
The original carma-messenger-core Dockerfile in the release/vanden-plas branch did not reference the correct base image.
A carma-messenger-core docker image was successfully built with these changes.

Dockerfile updates to enable carma-messenger-core Vanden Plas candidate image build

---

carma-messenger-core/hooks/pre_build

The release/autobuild_test branch is currently used to test regex updates to the hooks/pre_build files in this repo in an effort to test the release image auto build process on Docker Hub. Currently, there is one regex error on the release/autobuild_test branch, which causes the certain repositories to be checked out on their 'develop' branch during the image build process. This change seeks to fix that issue. Once this change is merged into release/autobuild_test, and the auto build process is verified, the next step will be to merge release/autobuild_test into develop.
This change is required in order to enable the carma-messenger-core image to successfully build automatically on Docker Hub for release branches.
The release/autobuild_test branch serves as the test for this change. After …

Regex updates in hooks/pre_build for release auto build process.

---

carma-messenger-config/chevrolet_tahoe_2018/hooks/pre_build
carma-messenger-config/development/hooks/pre_build
carma-messenger-core/hooks/pre_build

Fix pre_build hook to convert `develop` into release named docker images.

Adjust pre_build hook for release builds

---

carma-messenger-core/cpp_message/src/cpp_message.cpp

Day of week in TCM is encoded as bits. For example 254 int is 11111110 in binary which correspond to every day being available (last 0 is not used as there are 7 days and 8 bits). This PR makes sure it conforms to that.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1303
Found during RWM testing.
Local integration tested.

fixed dow bit-wise encoding/decoding

---

carma-messenger-core/cpp_message/CMakeLists.txt
carma-messenger-core/j2735_convertor/CMakeLists.txt
carma-messenger-core/traffic_incident/CMakeLists.txt
carma-messenger-core/truck_inspection_plugin/CMakeLists.txt

Update the CMakeLists.txt files to specify c++14 instead of C++11. 
Using C++ 14 to compile the CARMA source code on Ubuntu 20.04.
Full build and checking the output logs for C++ 14 usage.

Update ROS Noetic branch to C++14

---

carma-messenger-core/j2735_convertor/src/psm_convertor.cpp

This PR fixes issues with issues with conversion seen in j2735_convertor for PSM messages.
Some missing parameters were also added.
Locally integration tested

fix conversion units

---

carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp
carma-messenger-core/cpp_message/test/test_MobilityResponse.cpp

When adding fields to the MobilityResponse message, it was updated to use the new MobilityPlanType message, instead of the old PlanType message. This is unintended and causes a message mismatch.
The solution is to remove the new MobilityPlanType message, and instead add its new enum fields to the PlanType message, also updating the cpp_message file and relevant unit tests. These changes for both cav_msgs and carma_v2x_msgs.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1775

Changed cav_msgs/MobilityPlanType back to cav_msgs/PlanType

---

carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
carma-messenger-config/development/docker-compose.yml
carma-messenger-core/Dockerfile

Fixes a find/replace error in the dockerfile used for the 4.1.0 release. As a result the 4.1.1 hotfix is being created with this PR.

Fix find/replace error in Dockerfile

---

carma-messenger-core/cpp_message/src/BSM_Message.cpp
carma-messenger-core/cpp_message/test/node_test.cpp
carma-messenger-core/cpp_message/test/test_BSM.cpp

https://usdot-carma.atlassian.net/browse/CAR-5642 and resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1917
There was one for-sure memory leak in the code, brake_applied_status which was allocated with calloc but never freed. There were also 8 instances of potential memory corruption, where a variable was allocated with calloc, a pointer to its data stored into a field of the message, but was freed immediately. ex: the below image. Valgrind didn't detect this as an error, maybe because this specific encoder is so small that there is only a small chance that any individual block of memory is tampered with before the message is encoded and it is no longer needed. I searched around for a way to pull these kinds of errors out of the woodwork, but it may just have to be a …

Fixed potential memory corruption issues

---

carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
carma-messenger-core/cpp_message/test/node_test.cpp
carma-messenger-core/cpp_message/test/test_MobilityOperations.cpp

https://usdot-carma.atlassian.net/browse/CAR-5644 and resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1920
The code didn't have any memory leaks or memory corruption issues, but it was cleaned up a bit, and a unit test was added to detect memory corruption in the future. 
I added a new unit test, testEncodeDecodeMobilityOperationMsg, in test_MobilityOperations.cpp. If any field of the message is different after encoding/decoding, the test fails. I also ran valgrind to identify memory leaks while running the unit test. I wasn't able to fix all of the memory leaks, because some appear to be built into the asn1c uper encoder/decoder, ros, and the atoll function. More details on those here: https://usdot-carma.atlassian.net/wiki/spaces/CRMPLT/pages/2314469377/Checking+code+fo …

fix mobility operations message encoder memory

---

carma-messenger-core/cpp_message/include/cpp_message/MobilityRequest_Message.h
carma-messenger-core/cpp_message/src/MobilityRequest_Message.cpp
carma-messenger-core/cpp_message/test/node_test.cpp
carma-messenger-core/cpp_message/test/test_MobilityRequest.cpp

https://usdot-carma.atlassian.net/browse/CAR-5646 and resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1922
The code didn't have any memory leaks or memory corruption issues, but it was cleaned up a bit, and a unit test was added to detect memory corruption in the future. 
I added a new unit test, testEncodeDecodeMobilityRequestMsg, in test_MobilityRequest.cpp. If any field of the message is different after encoding/decoding, the test fails. I also ran valgrind to identify memory leaks while running the unit test. I wasn't able to fix all of the memory leaks, because some appear to be built into the asn1c uper encoder/decoder, ros, and the atoll function. More details on those here: https://usdot-carma.atlassian.net/wiki/spaces/CRMPLT/pages/2314469377/Checking+code+for+mem …

Cleaned up code, no memory leaks to fix

---

carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp
carma-messenger-core/cpp_message/test/node_test.cpp
carma-messenger-core/cpp_message/test/test_MobilityResponse.cpp

https://usdot-carma.atlassian.net/browse/CAR-5647 and resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1923
The code didn't have any memory leaks or memory corruption issues, but it was cleaned up a bit, and a unit test was added to detect memory corruption in the future. 
I added a new unit test, testEncodeDecodeMobilityResponseMsg, in test_MobilityResponse.cpp. If any field of the message is different after encoding/decoding, the test fails. I also ran valgrind to identify memory leaks while running the unit test. I wasn't able to fix all of the memory leaks, because some appear to be built into the asn1c uper encoder/decoder, ros, and the atoll function. More details on those here: https://usdot-carma.atlassian.net/wiki/spaces/CRMPLT/pages/2314469377/Checking+code+for+m …

No issues to solve, added a unit test

---

carma-messenger-core/emergency_response_vehicle_plugin/include/emergency_response_vehicle_plugin/emergency_response_vehicle_plugin_node.hpp
carma-messenger-core/emergency_response_vehicle_plugin/package.xml
carma-messenger-core/emergency_response_vehicle_plugin/src/emergency_response_vehicle_plugin_node.cpp
carma-messenger-core/emergency_response_vehicle_plugin/test/test_emergency_response_vehicle_plugin.cpp

This PR removes support for the emergency_response_vehicle_plugin's /get_emergency_route service callback, which originally included the name of the Emergency Response Vehicle's (ERV's) route destination in the service response. This change is required because the Emergency Response UI no longer calls the /get_emergency_route service to obtain the name of the ERV's route, since the route name is no longer displayed to the user. Instead, due to PR #177, the Emergency Response Web UI displays the ERV's current location and future route destination points on an interactive map.
In support of [CARMA Messenger Issue #173](https://github.com/usdot-fhwa-stol/carma-messenger/issues/173) and [CARMA Platform Issue #2031](https://github.com/usdot-fhwa-stol/carma-platform/issues/2031)
This service is …

Remove support for /get_emergency_route service from emergency_response_vehicle_plugin

---

carma-messenger-core/emergency_response_vehicle_plugin/config/parameters.yaml
carma-messenger-core/emergency_response_vehicle_plugin/include/emergency_response_vehicle_plugin/emergency_response_vehicle_plugin_config.hpp
carma-messenger-core/emergency_response_vehicle_plugin/src/emergency_response_vehicle_plugin_node.cpp
carma-messenger-core/emergency_response_vehicle_plugin/test/test_emergency_response_vehicle_plugin.cpp

This PR includes a couple of minor fixes to the emergency_response_vehicle_plugin in CARMA Messenger. Specifically, a bug is fixed in which `&&` was incorrectly being used for 'bitwise AND' operations, rather than the correct `&` in emergency_response_vehicle_plugin unit tests. Additionally, the BSM presence vector is not properly set to indicate that a regional extension is present when it is included in the BSM (this regional extension is used to include the ERV's future route destination points). Fixing this bug will enable to the plugin to properly include the ERV's future route destination points in its published BSMs. 
Additionally, this PR updates the default UDP listening port (on which it listens to incoming UDP packets that describe the activation status of an ERV's emergency …

Fix emergency_response_vehicle_plugin by enabling it to properly include an ERV's future route destination points in published BSMs

---

carma-messenger-ui/website/widgets/emergencyResponse/widget.css
carma-messenger-ui/website/widgets/emergencyResponse/widget.js

Adjust the WARNING message in web ui for CARMA messenger to be larger
https://github.com/usdot-fhwa-stol/carma-messenger/issues/195
Freight integration testing
NA

Adjust the WARNING message in web ui for CARMA messenger to be larger

---

carma-messenger-core/cpp_message/include/cpp_message/SDSM_Message.h
carma-messenger-core/cpp_message/src/SDSM_Message.cpp
carma-messenger-core/cpp_message/src/cpp_message.cpp
carma-messenger-core/cpp_message/test/test_SDSM.cpp
carma-messenger-core/j2735_convertor/.vscode/settings.json

Added SDSM decoder functionality to the CARMA Messenger "cpp_message" node to expand on the existing SDSM encoder files being SDSM_Message.h, SDSM_Message.cpp, and test_SDSM.cpp. This decoder takes inbound ASN.1 messages and decodes them into j2735_v2x_msgs/j3224_v2x_msgs usable by ROS2. Unit tests were added both for new code and in conjunction with previous encoder work to ensure the node can be used both ways.
(https://github.com/usdot-fhwa-stol/carma-messenger/issues/205)
CDAR-233
Allows incoming ASN.1 SDSMs to be interpreted by ROS for CARMA Messenger so that vehicles can interpret SDSM data from infrastructure.
Builds, previous unit tests pass, new unit tests pass, message data printed out to file and checked for validity.

Added SDSM decoder functionality to cpp_message node

---

carma-messenger-core/cpp_message/src/SDSM_Message.cpp

This PR fixes a segmentation fault during SDSM encoding caused by trying to copy the message's source ID. The `TemporaryID.msg`'s `id` field gets implemented as a `std::vector<std::uint8_t>`, which is not guaranteed to have any elements. The SDSM encoding function assumes that the `SensorDataSharingMessage.msg`'s `source_id` field has 4 elements.
This PR adds a size check before copying the data.
Closes [CDAR-775](https://usdot-carma.atlassian.net/browse/CDAR-775)
Bug fix
Manually in integration testing
[CDAR-775]: https://usdot-carma.atlassian.net/browse/CDAR-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[cpp_message] Fix segmentation fault when encoding SDSM messages

---

carma-messenger-core/emergency_response_vehicle_plugin/test/test_emergency_response_vehicle_plugin.cpp

Temporarily disabled old failing unit tests, to be able to use CI for new development
[CARMA Platform #2335](https://github.com/usdot-fhwa-stol/carma-platform/issues/2335)
https://usdot-carma.atlassian.net/browse/CAR-6008

disable unit test for emergency response vehicle

---

carma-messenger-core/j2735_convertor/include/j2735_convertor/control_message_convertor.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/control_request_convertor.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/j2735_convertor_node.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/map_convertor.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/psm_convertor.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/sdsm_convertor.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/spat_convertor.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/units.hpp
carma-messenger-core/j2735_convertor/include/j2735_convertor/value_convertor.hpp
carma-messenger-core/j2735_convertor/src/bsm_convertor.cpp
carma-messenger-core/j2735_convertor/src/control_message_convertor.cpp
carma-messenger-core/j2735_convertor/src/control_request_convertor.cpp
carma-messenger-core/j2735_convertor/src/psm_convertor.cpp
carma-messenger-core/j2735_convertor/src/sdsm_convertor.cpp
carma-messenger-core/j2735_convertor/test/control_message_test.cpp

This PR renames the `j2735_msgs` and `j322_msgs` packages after these packages were merged into `j2735_v2x_msgs` and `j3224_v2x_msgs` in [carma-msgs PR #243](https://github.com/usdot-fhwa-stol/carma-msgs/pull/243).
NA
[ARC-205](https://usdot-carma.atlassian.net/browse/ARC-205)
Old package names are outdated and no longer exist.
Only changes are comments, so testing is not required.
[ARC-205]: https://usdot-carma.atlassian.net/browse/ARC-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updated to reflect new j2735 and j3224 package names

---

carma-messenger-core/carma-messenger/launch/plugins.launch.py
carma-messenger-core/emergency_response_vehicle_plugin/config/parameters.yaml
carma-messenger-core/traffic_incident/launch/traffic_incident.launch.py
carma-messenger-ui/website/widgets/eventManagement/widget.js

This PR fixes the topic remapping for the pinpoint sensor, changing it from `/position` to `/hardware_interface`.
NA
[CAR-6063](https://usdot-carma.atlassian.net/browse/CAR-6063)
When ported to ROS2 in [carma-torc-pinpoint-driver#46](https://github.com/usdot-fhwa-stol/carma-torc-pinpoint-driver/pull/46), the CARMA Torc Pinpoint Driver namespace was changed to `/hardware_interface` to match the rest of the CARMA drivers. This same change is needed in CARMA Messenger to connect with the Pinpoint Driver.
Tested on the Chevrolet Tahoe. Testing included:
1. Adding the above changes into the necessary docker images.
2. Running CARMA Messenger
3. Checked that CARMA Messenger subscribed to the correct topics (`/hardware_interface/gps_common_fix` and `/hardware_interface/velocity`)
4. Verified …

Pinpoint Topic Remapping

---

carma-messenger-ui/website/widgets/eventManagement/widget.js

This PR resolves an issue where the GPS coordinates reported by the Pinpoint device do not show up in the CARMA Messenger Traffic Incident Management plugin.
NA
[CRA-6063](https://usdot-carma.atlassian.net/browse/CAR-6063)
This change results in the GPS coordinate being populated correctly.
Tested on the Chevy Tahoe. Confirmed that coordinates are loaded sucessfully

Fix GPS Coordinates not Showing Up in Traffic Incident Plugin

---

carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp

This PR fixes the timestamp calculation for the generated mobility message. Currently the package uses the second field from the GPSFix message constructed from the torc pinpoint driver's input, but ideally the nanosecond field should also be used.
The fix updates the implementation by converting the header field to a nanoseconds value which is then used to calculate the required timestamp in milliseconds.

fix time from header calc

---

carma-messenger-core/carma-messenger/CMakeLists.txt
carma-messenger-core/carma-messenger/launch/carma-messenger.launch.py

This PR fixes an issue in the carma-messenger launch script causing the ros2 rosbag recording to error out.
The ThisLaunchFileDir() option being placed after get_package_share_directory calls causes ThisLaunchFileDir() substitution to take the value of the last get_package_share_directory().
In this update the ros2 rosbag record launch option was moved to the start of the script as a workaround.
Additionally the required config directory from the carma-messenger package was added to installation.

Fix ros2bag launch

---

.github/workflows/ci.yml
carma-messenger-core/docker/checkout.bash
carma-messenger-core/docker/install.sh
carma-messenger-core/docker/install_dependencies.sh

This PR updates the installation for the stol-j2735 library to use the correct version based on branch and ubuntu distro.

update install_deps for v2x-ros-conversion
