usdot-fhwa-stol/carma-messenger

- .circleci/config.yml
- README.md
- config/development/docker-compose.yml
- docker/checkout.sh
- message/CMakeLists.txt
Updates the readme instructions to be more accurate and fixes some tag issues in the docker config. 
This PR supports usdot-fhwa-stol/CARMAPlatform#606
> Update instructions and image tags

- truck_inspection_plugin/CMakeLists.txt
- truck_inspection_plugin/config/parameters.yaml
- truck_inspection_plugin/include/truck_inspection_plugin.h
- truck_inspection_plugin/launch/truck_inspection_plugin.launch
- truck_inspection_plugin/package.xml
- truck_inspection_plugin/src/main.cpp
- truck_inspection_plugin/src/truck_inspection_plugin.cpp
Initial commit for Truck Inspection Plugin, which contains logic to work with UI and sends out truck safety log request.
Implement https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/613
> Truck Inspection Plugin

- truck_inspection_plugin/CMakeLists.txt
- truck_inspection_plugin/config/parameters.yaml
- truck_inspection_plugin/include/truck_inspection_plugin.h
- truck_inspection_plugin/package.xml
- truck_inspection_plugin/src/truck_inspection_plugin.cpp
- truck_inspection_plugin/test/test_launch.test
- truck_inspection_plugin/test/test_truck_inspection_plugin.cpp
Address adding two fields (state and ads_auto_status) and change the ads_status to ads_health_status
update parameters to 14
update the publish VIN topic to publish "VIN, State, License plate"
Added Unit testing code
> init commit update truck inspection plugin for CAR-2122

- carma-messenger-ui/website/widgets/truckInspection/widget.css
minor layout issue
Test and run in local VM
UI layout
[CARMA Contributing Guide](Contributing.md)
> CARMA Messenger - Truck Inspection UI - Update 

- carma-messenger-core/cpp_message/launch/cpp_message.launch
Fix broken launch file.
N/A
File xml file format.
Integration tested.
> Launch file fix

- carma-messenger-config/development/build-image.sh
- carma-messenger-config/development/docker-compose.yml
Changes in this PR are to update the carma-messenger-config build scripts with the -d option
needed for integration testing option
successful build with the build-image.sh -d option
> updated for develop builds

- carma-messenger-core/docker/checkout.bash
- carma-messenger-core/j2735_convertor/include/j2735_convertor/control_request_convertor.h
- carma-messenger-core/j2735_convertor/src/control_request_convertor.cpp
- carma-messenger-core/j2735_convertor/src/j2735_convertor.cpp
- carma-messenger-core/j2735_convertor/src/j2735_convertor.h
- carma-messenger-core/j2735_convertor/src/main.cpp
- carma-messenger-core/j2735_convertor/test/control_request_test.cpp
To support this the j2735_convertor node needs to be updated for the new ROS messages and ASN1 spec.
- [x ] New feature (non-breaking change that adds functionality)
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
> control_request

- carma-messenger-core/carma-messenger/package.xml
- carma-messenger-core/cpp_message/package.xml
- carma-messenger-core/j2735_convertor/package.xml
- carma-messenger-core/lib_asn1c/package.xml
- carma-messenger-core/message/package.xml
- carma-messenger-core/truck_inspection_plugin/package.xml
PR for updating package.xml files.
Changed package.xml files for every package in this repository to format 3.
This change is required to move carma to newer software.
This has been tested by successfully building this repository.
> Updated package.xml files PR

- carma-messenger-core/cpp_message/CMakeLists.txt
- carma-messenger-core/cpp_message/include/MobilityHeader_Message.h
- carma-messenger-core/cpp_message/include/MobilityPath_Message.h
- carma-messenger-core/cpp_message/include/cpp_message.h
- carma-messenger-core/cpp_message/src/MobilityHeader_Message.cpp
- carma-messenger-core/cpp_message/src/MobilityPath_Message.cpp
- carma-messenger-core/cpp_message/src/cpp_message.cpp
- carma-messenger-core/cpp_message/test/test_MobilityPath.cpp
- carma-messenger-core/message/message/src/main/java/gov/dot/fhwa/saxton/carma/message/factory/DSRCMessageFactory.java
Conversion of Mobility Path messages from Java to cpp.
To support the upgrade to ROS1 Noetic and ROS2 all java code must be removed from the system. This story is part of a set of stories to convert the java message package to C++ and integrate its logic with the newer message_cpp package. 
MobilityPath cpp and header files were added to cpp_message directory. The cpp node was extended to deal with MobilityPath messages. 
A unit test was created for testing encoding and decoding functions.
To support the upgrade to ROS1 Noetic and ROS2 all java code must be removed from the system.
A unit test was created using the data from the Java code.
Encoding parameters from the Java node was used to test the encoding function. The binary output from the test was fed into the decoding function and …
> Mobility path on new branch for easier integration

- carma-messenger-core/truck_inspection_plugin/launch/truck_inspection_plugin.launch
Update truck inspection plugin launch file remapping
https://github.com/usdot-fhwa-stol/carma-platform/issues/871
ACE testing
Integration testing in vehicle
> update launch remapping

- carma-messenger-core/cpp_message/src/MobilityPath_Message.cpp
Updating constant name in Mobility Path 
> updating constant name

- carma-messenger-config/chevrolet_tahoe_2018/hooks/pre_build
- carma-messenger-core/hooks/pre_build
PR fixes hook layout to avoid hardcoding image names into docker related files
> fixed hook layout

- carma-messenger-core/carma-messenger/launch/carma-messenger.launch
- carma-messenger-core/traffic_incident/CMakeLists.txt
- carma-messenger-core/traffic_incident/config/parameters.yaml
- carma-messenger-core/traffic_incident/include/traffic_incident_node.h
- carma-messenger-core/traffic_incident/include/traffic_incident_worker.h
- carma-messenger-core/traffic_incident/launch/traffic_incident.launch
- carma-messenger-core/traffic_incident/package.xml
- carma-messenger-core/traffic_incident/src/main.cpp
- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
- carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp
- carma-messenger-core/traffic_incident/test/main.cpp
- carma-messenger-core/traffic_incident/test/test_traffic.cpp
Traffic Incident node is a standalone ROS node in the CARMA Messenger. It collects data from Pinpoint driver node (e.g., latitude, longitude, heading). The traffic incident node will take the GPS data (Latitude, Longitude, Heading (Optional)),vehicle ID, up track and down track distance (It will be blocking the nearest lane for the indicated uptrack and downtrack distance from the Tahoe's position ) and publish as MobilityOperation message to the outgoingMobilityOperation topic. This will make the CARMA messenger to broadcast the Mobility Message. Please read detailed design CARMA Messenger Traffic Incident Node for more information.
https://github.com/usdot-fhwa-stol/carma-platform/issues/961
Enhancement for traffic incident use case.
[CARMA Contributing …
> traffic_incident_use_case

- carma-messenger-config/chevrolet_tahoe_2018/carma.config.js
- carma-messenger-config/development/carma.config.js
- carma-messenger-ui/website/scripts/carma.config.js
- carma-messenger-ui/website/widgets/truckInspection/widget.js
The truck image display a flashing broken link when invalid VIN number is received
https://github.com/usdot-fhwa-stol/carma-platform/issues/992
ACE testing
Local integration testing 
JS logic change
> Fix #992: carma-messenger UI - Truck picture not showing consistently

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose-background.yml
- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
- carma-messenger-config/development/docker-compose-background.yml
- carma-messenger-config/development/docker-compose.yml
Updates the carma-messenger-core configs to point at the correct component versions for the 3.4.1 release. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1010
Correct behavior when launching carma-messenger for the 3.4.* releases
> Use component versions in docker compose

- .circleci/config.yml
- .sonarqube/sonar-scanner.properties
- carma-messenger-core/traffic_incident/config/parameters.yaml
- carma-messenger-core/traffic_incident/include/traffic_incident_node.h
- carma-messenger-core/traffic_incident/include/traffic_incident_worker.h
- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
- carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp
- carma-messenger-core/traffic_incident/test/test_traffic.cpp
See below.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1045
Though not covered in the HLD doc, the incident use case needs to include the Tahoe providing a constraint on the minimum following gap for vehicles in the area. This story is to add that parameter to the message sent by the Tahoe that will limit the following distance in meters. This value can be passed into the TrafficControlDetail message as the minhdwy parameter. 
Unit tested
- [X ] I have added any new packages to the sonar-scanner.properties file
> Add gap distance to traffic incidence 

- carma-messenger-core/hooks/pre_build
Changes have been made to the hooks/pre_build file within carma-messenger-core in order to enable Docker Hub to successfully build a carma-messenger-core candidate image for release branches. Prior to these changes, the pre_build file did not provide the correct path to the carma-messenger-core Dockerfile and checkout.bash script, causing the Docker Hub auto build to fail.
Without these updates, carma-messenger-core candidate images cannot be automatically triggered/built from Docker Hub, since the hooks/pre_build file included incorrect paths to the necessary Dockerfile and checkout.bash script.
> carma-messenger-core pre_build updates to enable Docker Hub auto build for release branches

- carma-messenger-core/traffic_incident/CMakeLists.txt
- carma-messenger-core/traffic_incident/include/traffic_incident_node.h
- carma-messenger-core/traffic_incident/include/traffic_incident_worker.h
- carma-messenger-core/traffic_incident/package.xml
- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
- carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp
- carma-messenger-core/traffic_incident/test/test_traffic.cpp
The CARMA Messenger core component requires a new ROS node: Traffic Incident Publisher Node. This node allows to respond to front end UI request and gather the required information from front UI. Based on the required information, this node will construct Mobility messages and publish the necessary information to Message Node. The Message Node will forward this mobility message to DSRC driver, then to OBU. The OBU broadcast the information. Nearby vehicle equipped with OBU can receive this information and respond as needed. Traffic Incident Publisher Node is also responsible for stopping publishing Geofence information to Message Node.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1095
Traffic Incident Use Case
Local Integration testing
[CARMA Contributing …
> Traffic Incident Management : CARMA -Messenger: Update Traffic Incident Publisher Node for Messenger UI

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose-background.yml
- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
- carma-messenger-config/development/docker-compose-background.yml
- carma-messenger-config/development/docker-compose.yml
- carma-messenger-core/Dockerfile
- carma-messenger-core/docker/checkout.bash
Follow up for https://github.com/usdot-fhwa-stol/carma-messenger/pull/79 to update version numbers for develop
> Update version numbers for master sync

- carma-messenger-core/traffic_incident/config/parameters.yaml
- carma-messenger-core/traffic_incident/include/traffic_incident_node.h
- carma-messenger-core/traffic_incident/include/traffic_incident_worker.h
- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
- carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp
- carma-messenger-core/traffic_incident/test/test_traffic.cpp
Update the Traffic Incident Parser node in CARMA Platform and CARMA Messenger to handle Vehicle Type and Event Reason
Incident Use Case
> vehicle_type_vehicle_reason

- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
Update mobilityOperation message broadcasting rate to 10HZ
N/A
Traffic Incident use case
Local integration testing
> UI broadcast rate to 10HZ

- carma-messenger-core/traffic_incident/include/traffic_incident_worker.h
- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
- carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp
Refactor start broadcasting and update precision to 8 decimal places
N/A
Traffic Incident use case
Local Integration testing
> Refactor start broadcasting and update precision to 8 decimal places

- carma-messenger-core/cpp_message/src/cpp_message.cpp
The changes in this PR add necessary information to published TrafficControl messages to ensure that the messages can be properly interpreted by carma-cohda-dsrc-driver before being outputted to a connected OBU.
Related PR: [carma-cohda-dsrc-driver "Add TrafficControl messages to wave.json"](https://github.com/usdot-fhwa-stol/carma-cohda-dsrc-driver/pull/60)
This supports new functionality - CARMA vehicles with a properly configured OBU will be able to transmit TrafficControlRequest and TrafficControlMessage messages.
Integration tested on the Chevy Tahoe and White Pacifica (both have acted as the transmitting and receiving vehicle).
> Update published TrafficControl binary messages

- carma-messenger-ui/website/widgets/eventManagement/widget.js
Update advisory speed unit of measure display on the UI to MPH
N/A
Traffic Incident use case
Local Integration testing
> Advisory Speed unit of measure to MPH

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
- carma-messenger-config/chevrolet_tahoe_2018/drivers.launch
- carma-messenger-config/development/docker-compose.yml
- carma-messenger-config/development/drivers.launch
update docker-compose to include pinpoin driver
N/A
Traffic incident use case
will be tested in vehicle
> update docker-compose to include pinpoin driver

- carma-messenger-core/truck_inspection_plugin/src/truck_inspection_plugin.cpp
Same as https://github.com/usdot-fhwa-stol/carma-platform/pull/1216
> Set spin rate in truck_inspection_plugin

- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
update spin rate 
N/A
traffic Incident use case
in Taheo
> update spin rate 

- carma-messenger-core/traffic_incident/launch/traffic_incident.launch
- carma-messenger-ui/website/widgets/eventManagement/widget.js
Remap gps_common_fix to /position/gps_common_fix
N/A
Traffic Incident use case
In Taheo
> Remap gps_common_fix to /position/gps_common_fix

- carma-messenger-config/chevrolet_tahoe_2018/carma.config.js
- carma-messenger-config/development/carma.config.js
- carma-messenger-ui/website/scripts/carma.config.js
- carma-messenger-ui/website/widgets/eventManagement/widget.js
The zephyr verification test plan requires that the carma-messenger incident UI validate user inputs to keep them to reasonable ranges.
This should be added.
The desired ranges are.
```
uptrack [1, 1000]
downtrack[1, 1000]
min_gap [1, 250]
speed limit [1, 80]
```
https://github.com/usdot-fhwa-stol/carma-platform/issues/1251
Local Integration testing
> carma-messenger traffic incident UI should have input validation

- carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
V2XHub transmits MobilityOperation messages with each set of quotation marks encoded as `&quot;` within the strategy_params string field. This causes strategy_params parsing issues in carma-platform. To fix this issue, a line of code is introduced within MobilityOperation_Message.cpp to convert all occurrences of `&quot;` in the strategy_params field into `/".` 
Related PR in carma-platform repository: [Add incoming MobilityOperation message processing to Port Drayage Plugin](https://github.com/usdot-fhwa-stol/carma-platform/pull/1252)
See above.
Integration tested with White Pacifica and V2XHub.
> Replace encoded quotation marks in received MobilityOperation message's strategy_params field

- carma-messenger-core/docker/checkout.bash
Signed-off-by: pmusau17 <pmusau13ster@gmail.com>
Adding branch tags for the noetic port of the carma platform.
Changes needed to complete the noetic port of CARMA.
> checkout tags

- carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
PR #91 ("Replace encoded quotation marks in received MobilityOperation message's strategy_params field") was accidentally reverted by PR #95 (Release/zephyr). This PR re-introduces the updates from PR #91. These updates are required in order for carma-platform to properly parse text within the 'strategy_params' field of a received MobilityOperation message. 
Integration tested on Black Pacifica with V2XHub.
> Re-add updates from PR #91 to cpp_message package

- carma-messenger-core/cpp_message/CMakeLists.txt
- carma-messenger-core/cpp_message/include/Map_Message.h
- carma-messenger-core/cpp_message/include/SPAT_Message.h
- carma-messenger-core/cpp_message/include/cpp_message.h
- carma-messenger-core/cpp_message/src/Map_Message.cpp
- carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
- carma-messenger-core/cpp_message/src/SPAT_Message.cpp
- carma-messenger-core/cpp_message/src/cpp_message.cpp
- carma-messenger-core/cpp_message/test/test_MapMessage.cpp
- carma-messenger-core/cpp_message/test/test_SPAT.cpp
> Sync noetic with develop after 3.8.0 release

- carma-messenger-config/chevrolet_tahoe_2018/build-image.sh
- carma-messenger-config/chevrolet_tahoe_2018/hooks/pre_build
- carma-messenger-config/development/build-image.sh
- carma-messenger-config/development/hooks/pre_build
- carma-messenger-core/docker/build-image.sh
- carma-messenger-core/docker/checkout.bash
- carma-messenger-core/hooks/pre_build
- carma-messenger-ui/docker/build-image.sh
This PR syncs the Elise release with the changes from 3.9.0
Supports elise milestone https://github.com/usdot-fhwa-stol/carma-platform/milestone/5
Testing will occur on release branch after merge
> Sync Elise release with 3.9.0 release

- carma-messenger-core/j2735_convertor/src/psm_convertor.cpp
This pr fixes unit conversion for path prediction parameter confidence.
> fix confidence conversion

- carma-messenger-core/cpp_message/src/cpp_message.cpp
Adds a log statement for recording timestamp of incoming psm message.
> add debug log for psm timestamp

- carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp
- carma-messenger-core/cpp_message/test/test_MobilityResponse.cpp
The last PR for cav_msgs and carma_v2x_msgs made them different, this fixes that issue. 
> Fixed differences between cav_msgs and carma_v2x_msgs

- README.md
This PR is to add the dockerhub build status checks to readme
> added docker build checks to readme

- carma-messenger-core/cpp_message/src/MobilityPath_Message.cpp
- carma-messenger-core/cpp_message/test/test_MobilityPath.cpp
https://usdot-carma.atlassian.net/browse/CAR-5645 and resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1921
The code didn't have any memory leaks or memory corruption issues, but it was cleaned up a bit, and a unit test was added to detect memory corruption in the future. I also ran clang-format as vs code's c++ style on both the encoder and unit test files. This probably means that most lines of code are changed. The first commit doesn't have the formatting changes, so you can take a look at that. 
I added a new unit test, testEncodeDecodeMobilityPathMsg, in test_MobilityPath.cpp. If any field of the message is different after encoding/decoding, the test fails. I also ran valgrind to identify memory leaks while running the unit test. I wasn't able to fix all of the …
> mobility path encoder memory check and fixes

- README.md
README.md: add link to Doxygen page
> README.md: add link to Doxygen page

- carma-messenger-core/cpp_message/src/BSM_Message.cpp
- carma-messenger-core/cpp_message/src/Map_Message.cpp
- carma-messenger-core/cpp_message/src/MobilityOperation_Message.cpp
- carma-messenger-core/cpp_message/src/MobilityRequest_Message.cpp
- carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp
- carma-messenger-core/cpp_message/src/PSM_Message.cpp
- carma-messenger-core/cpp_message/src/SPAT_Message.cpp
- carma-messenger-core/cpp_message/src/cpp_message.cpp
Added struct free commands to release memory from the asn uper_decode operations. The uper_decode function allocates a structure that needs to be freed with these commands. This was found in previous memory fixes, and is being implemented in un-fixed files as well as previously fixed files, before this change was known. 
https://usdot-carma.atlassian.net/browse/CAR-5710 and resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1955. 
Used valgrind to test the changes in cpp_message, and the rest were tested with the existing unit tests. 
> asn_struct_free fixes

- carma-messenger-core/hooks/pre_build
- carma-messenger-ui/docker/install.sh
This PR is about to fix carma-messenger core and UI builds in docker hub candidate and dev organizations.
> Fix/messenger core and messenger UI docker hub builds

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
- carma-messenger-config/chevrolet_tahoe_2018/drivers.launch.py
- carma-messenger-config/development/docker-compose.yml
- carma-messenger-config/development/drivers.launch.py
- carma-messenger-core/carma-messenger/launch/message.launch.py
This PR includes a couple of updates to address CARMA Messenger launch issues which were impeding testing for the Emergency Response Use Case. Specifically, the dsrc_driver_node (from the carma-cohda-dsrc-driver repo) was not being configured or activated at launch, and a fix has been implemented for that. Additionally, the ros1_bridge was not being launched with `--multi_threads`, which was causing significant delay in ROS messages being bridged from ROS1 to ROS2 on high-frequency topics (most notably the /position/gps_common_fix, which had messages published to it at ~100 Hz).
[Issue #190](https://github.com/usdot-fhwa-stol/carma-messenger/issues/190)
[Issue #191](https://github.com/usdot-fhwa-stol/carma-messenger/issues/191)
See issues listed previously.
Integration tested on Chevy …
> Launch fixes to support Emergency Response Use Case

- .vscode/settings.json
- carma-messenger-core/emergency_response_vehicle_plugin/include/emergency_response_vehicle_plugin/emergency_response_vehicle_plugin_node.hpp
- carma-messenger-core/emergency_response_vehicle_plugin/src/emergency_response_vehicle_plugin_node.cpp
- carma-messenger-core/emergency_response_vehicle_plugin/test/test_emergency_response_vehicle_plugin.cpp
This PR includes a small fix within emergency_response_vehicle_plugin to correctly process the first byte of received UDP packets from a connected raspberry pi device. Originally, this plugin assumed the first byte would equate to values 1,2,3, and 4; however, the first byte actually equates to the value of char '1', '2', '3', and '4'. These values indicate the status of an emergency response vehicle's sirens and lights and are specific to the raspberry device setup in the STOL developer team's CARMA Messenger vehicle.
Issue #193 
This fix is required for the emergency_response_vehicle_plugin to correctly identify the current status of the emergency response vehicle's sirens and lights.
Integration tested on the Chevy Tahoe (equipped with CARMA Messenger)
> Fix received UDP binary processing in emergency_response_vehicle_plugin

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
This PR adds an environment variable for cyclone dds. The environment variable points to a configuration file in the /opt/carma/maps directory. 
Since the Tahoe doesn't have a calibration folder, this file is currently manually created on the vehicle.
This change is required to be able to broadcast ros2 data outside the vehicle pc for use in the work force development tool.
Integration Tested on Tahoe
> add cyclone config

- carma-messenger-config/development/docker-compose.yml
This PR adds volume to the messenger ros2 container, allowing the container to access the vehicle calibration.
This fixes an issue where launching carma-messenger on the development environment throws an error about a missing urdf file.
Locally Integration tested.
> add volume to vehicle calibration

- carma-messenger-config/example_calibration_folder/README.md
- carma-messenger-config/example_calibration_folder/vehicle/calibration/urdf/carma.urdf
Recent update to carma-messenger in https://github.com/usdot-fhwa-stol/carma-messenger/pull/186 adds a dependency to a vehicle calibration file (carma.urdf). This PR adds an example calibration for carma-messenger to enable running it successfully on a local development environment.
This sample calibration directory under carma-messenger/carma-messenger-config/example_calibration_folder/vehicle will need a symlink created at /opt/carma/vehicle in order to allow carma-messenger to start successfully.
> add example calibration

- .github/workflows/docker.yml
- carma-messenger-core/cpp_message/src/SDSM_Message.cpp
- carma-messenger-core/cpp_message/test/test_SDSM.cpp
The SDSM decoder is treating every field as if optional and doing if check whether if the field is available.
However, this check is should not be done on required fields because the required field may have 0 as a valid entry but the if value == 0 check may erroneously detect that the field is unavailable and set it to unavailable status (for example 0 speed is valid). This if check should only be present for the optional fields in asn1 spec.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2263
CDAR-634
https://usdot-carma.atlassian.net/browse/CDAR-634
Integration tested on Simulation 1 PC, all unit tests pass
- [X ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
> Fix sdsm decoder optional fields

- carma-messenger-core/emergency_response_vehicle_plugin/test/test_emergency_response_vehicle_plugin.cpp
This PR updates a unit test in emergency_response_vehicle_plugin which to use` ament_index_cpp::get_package_share_directory()` to access a csv file with route destinations. This fixes the unit test which was failing previously.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2335
> fix file loading for unit test

- carma-messenger-core/cpp_message/test/test_MobilityRequest.cpp
Disable intermittently failing unit test in order to allow CI to complete on new PRs. 
This test seems to be failing at times due to time taken by the service calls being tested. 
This PR disables a unit test that is failing intermittently on CI.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2335
[CAR-6044](https://usdot-carma.atlassian.net/browse/CAR-6044)
[CAR-6044]: https://usdot-carma.atlassian.net/browse/CAR-6044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> disable unit test for CI

- carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp
develop-humble mirror PR of: 
https://github.com/usdot-fhwa-stol/carma-messenger/pull/231
> fix header time develop-humble 

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
- carma-messenger-config/development/docker-compose.yml
- carma-messenger-core/Dockerfile
Removing `wait-for-it.sh` symlink to `wait-for-it` because it is not needed.
NA
NA
Upgrade to ROS2 Humble, thought I might fix this.
Tested this on previous 4.5.0 image by removing the symlink the package itself works fine directly
> remove wait-for-it-sh dependence

- carma-messenger-core/carma-messenger/config/rosbag2_qos_overrides.yaml
- carma-messenger-core/carma-messenger/launch/carma-messenger.launch.py
- carma-messenger-core/carma-messenger/launch/ros2_rosbag.launch.py
This PR adds ros2 rosbag recording to carma-messenger.
Tested locally.
> add ros2 rosbag recording

- carma-messenger-core/traffic_incident/include/traffic_incident_node.hpp
- carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp
This PR updates the filter for traffic incident plugin to not check for minimum gap values since that parameter is not used and checks for the other parameters as an or condition. Since stop_broadcast service call is resets all parameters to zero - this "or " condition should result in the desired response.
> update parameter filter for traffic incident plugin

- carma-messenger-config/chevrolet_tahoe_2018/.env
- carma-messenger-config/development/.env
- carma-messenger-core/Dockerfile
This PR is to update release/prowler  branch to point new carma-system-4.9.0 and STOL org form candidate for validation testing and releasing.
> Update Config files To Point New version

- carma-messenger-config/chevrolet_tahoe_2018/docker-compose.yml
- carma-messenger-core/carma-messenger/launch/carma-messenger.launch.py
Changes made to support the ros2 humble integration testing. Cyclone dds config parameter was removed since the NetworkInterfaceAddress parameter in the calibration file is not supported.  
Issue logged here - https://usdot-carma.atlassian.net/browse/WFD-608
It was also seen that the v2x-ros-conversion launch file includes node lifecycle transitions based on a timer which is currently getting skipped when the launch file is included as a group action.
Current workaround is just to call the operation as a process.
https://usdot-carma.atlassian.net/browse/ARC-276
> Tahoe Integration testing update

- .github/workflows/dockerhub.yml
- carma-messenger-config/chevrolet_tahoe_2018/.env
- carma-messenger-config/development/.env
- carma-messenger-core/Dockerfile
- carma-messenger-core/docker/checkout.bash
> Update the docker org and tag

- carma-messenger-config/chevrolet_tahoe_2018/.env
- carma-messenger-config/development/.env
This PR is to update release/stingray branch to point new carma-system-4.10.0 and STOL organization
[ARC-407](https://usdot-carma.atlassian.net/browse/ARC-407)
CI logs will be inspected for this testing
[ARC-407]: https://usdot-carma.atlassian.net/browse/ARC-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Config files To Point New version 4.10.0
